local options = {
    ensure_installed = {
        "bash",
        "c",
        "cmake",
        "comment",
        "cpp",
        "css",
        "dart",
        "dockerfile",
        "git_config",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        -- "haskell",
        -- "haskell_persistent",
        "html",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "powershell",
        "printf",
        "python",
        "rust",
        "sql",
        "ssh_config",
        "templ",
        "tmux",
        "toml",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        -- "zig",
    },

    highlight = {
        enable = true,
        use_languagetree = true,
    },

    indent = { enable = true },
}

require("nvim-treesitter.configs").setup(options)
